### ISSUE TITLE
Failed to connect: Connection refused

### ISSUE THREAD

**Issue by PegasusPool** [input-output-hk/cardano-graphql#179]
I followed the instructions [here](https://github.com/input-output-hk/cardano-graphql/wiki/Docker
) 
Started the containers with `docker-compose up -d` then got the logs via `docker-compose logs -f`

GraphQL is not accessible:

```
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardano { blockHeight }}"}' http://localhost:3100/graphql

curl: (7) Failed to connect to localhost port 3100: Connection refused
```
# Logs
The node is up for the last 20hours and synced, there's no visible error in the logs
![Screenshot from 2020-05-17 15-58-04](https://user-images.githubusercontent.com/58512297/82152131-3828dc00-9857-11ea-8957-f4f6bf1bf5ad.png)

# Containers

GraphQL exited with code 0

![Screenshot from 2020-05-17 19-20-48](https://user-images.githubusercontent.com/58512297/82156564-a4193d80-9873-11ea-894f-9a5a2a798041.png)

# Processes

![Screenshot from 2020-05-17 19-22-18](https://user-images.githubusercontent.com/58512297/82156589-da56bd00-9873-11ea-9ec9-02e341eddbbc.png)

# Error from cardano-graphQl

```
mask@mask-desktop:~/git/cardano-graphql$ sudo docker-compose logs | grep graph
Attaching to cardano-graphql_cardano-db-sync-extended_1, cardano-graphql_hasura_1, cardano-graphql_postgres_1, cardano-graphql_cardano-graphql_1, cardano-graphql_cardano-node_1
cardano-graphql_1           | Hasura schema introspection: Attempt 1 of 3, retying...
cardano-graphql_1           | Hasura schema introspection: Attempt 2 of 3, retying...
cardano-graphql_1           | Hasura schema introspection: Attempt 3 of 3, retying...
cardano-graphql_1           | Hasura schema introspection: Attempt 4 of 3, retying...
cardano-graphql_1           | { FetchError: request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.18.0.5:8080
cardano-graphql_1           |     at ClientRequest.<anonymous> (/application/node_modules/node-fetch/lib/index.js:1455:11)
cardano-graphql_1           |     at ClientRequest.emit (events.js:189:13)
cardano-graphql_1           |     at Socket.socketErrorListener (_http_client.js:392:9)
hasura_1                    | {"timestamp":"2020-05-16T21:08:51.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 9691"}}
cardano-graphql_1           |     at Socket.emit (events.js:189:13)
cardano-graphql_1           |     at emitErrorNT (internal/streams/destroy.js:82:8)
cardano-graphql_1           |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
cardano-graphql_1           |     at process._tickCallback (internal/process/next_tick.js:63:19)
hasura_1                    | {"timestamp":"2020-05-16T21:09:22.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 9691"}}
cardano-graphql_1           |   message:
cardano-graphql_1           |    'request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.18.0.5:8080',
cardano-graphql_1           |   type: 'system',
cardano-graphql_1           |   errno: 'ECONNREFUSED',
cardano-graphql_1           |   code: 'ECONNREFUSED',
cardano-graphql_1           |   attemptNumber: 4,
cardano-graphql_1           |   retriesLeft: 0 }
hasura_1                    | {"level":"info","msg":"Help us improve Hasura! The cli collects anonymized usage stats which\nallow us to keep improving Hasura at warp speed. To opt-out or read more,\nvisit https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html\n","time":"2020-05-16T21:09:23Z"}
hasura_1                    | {"type":"startup","timestamp":"2020-05-16T21:09:22.529+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html"}}
hasura_1                    | {"timestamp":"2020-05-16T21:09:25.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"graphql-engine will now start in normal mode"}}
hasura_1                    | {"type":"startup","timestamp":"2020-05-16T21:09:26.242+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
hasura_1                    | {"type":"startup","timestamp":"2020-05-16T21:09:26.242+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html"}}

```

**Comment by PegasusPool** [comment]
The issue was that nginx on the machine was using port 8080 and since hasura was configured to use the same port graphql engine failed to start. Working as expected after stopping nginx and making port 8080 available.

**Comment by rhyslbw** [comment]
Thanks for the detailed report @PegasusPool. The failure you experienced here was not related to a host port clash, as that would be apparent when starting the stack. In the boilerplate compose file, Hasura is actually [mapped to host port 8090](https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml#L48)

The `cardano-graphql` server currently only boots once Hasura is completely provisioned, which during the initial sync can be an extended period of time. It's something we'll be improving soon, but I've just added additional info to the [wiki](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#start-in-detached-mode-then-view-output-from-containers) that most likely would have worked for you in this situation.

**Comment by PegasusPool** [comment]
You are right @rhyslbw 
Thank you for explaining and adding the extra bit on the wiki. It will definitely help others before it's improved.
