### ISSUE TITLE
Stuck on Epoch 210

### ISSUE THREAD

**Issue by acewf** [input-output-hk/cardano-graphql#292]
Hi tried to use the repo, but seems always gets stuck on Epoch 210 
seems it can't connect to socket or subscribe to the peers
the logs looks to be looping the following message
```
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:485] [2020-09-07 17:18:55.53 UTC] [String "Connection Attempt Start, destination 54.177.232.179:3001",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:486] [2020-09-07 17:18:55.55 UTC] [String "Connection Attempt Start, destination 18.156.143.30:3001",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:487] [2020-09-07 17:18:55.58 UTC] [String "Connection Attempt Start, destination 52.52.61.248:3001",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:486] [2020-09-07 17:18:55.60 UTC] [String "Connection Attempt End, destination 18.156.143.30:3001 outcome: ConnectSuccess",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:488] [2020-09-07 17:18:55.61 UTC] [String "Connection Attempt Start, destination 54.93.82.235:3001",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:489] [2020-09-07 17:18:55.64 UTC] [String "Connection Attempt Start, destination 18.132.159.229:3001",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:503] [2020-09-07 17:18:55.66 UTC] [String "Connection Attempt Start, destination 18.180.136.78:3001",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Notice:488] [2020-09-07 17:18:55.66 UTC] [String "Connection Attempt End, destination 54.93.82.235:3001 outcome: ConnectSuccessLast",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.ErrorPolicy:Notice:71] [2020-09-07 17:18:55.66 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "54.177.232.179:3001"]
cardano-node_1              | [83e47172:cardano.node.ErrorPolicy:Notice:71] [2020-09-07 17:18:55.66 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "52.52.61.248:3001"]
cardano-node_1              | [83e47172:cardano.node.ErrorPolicy:Notice:71] [2020-09-07 17:18:55.67 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "18.132.159.229:3001"]
cardano-node_1              | [83e47172:cardano.node.ErrorPolicy:Notice:71] [2020-09-07 17:18:55.67 UTC] [String "ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = \"Parallel connection cancelled\", seStack = []}))) 1s",String "ErrorPolicyTrace",String "18.180.136.78:3001"]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Error:486] [2020-09-07 17:18:55.80 UTC] [String "Application Exception: 18.156.143.30:3001 HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789022}) ef28254a3ebf0bd6a7346138a3c27a90a165aee6f8c3176539b92979996a87f4 (BlockNo {unBlockNo = 4555189})) (Tip (SlotNo {unSlotNo = 7932827}) 93fb69de586d93662108eac490f26859eb0fd9ce858659f837d95563d83deb13 (BlockNo {unBlockNo = 4661463}))",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.ErrorPolicy:Warning:71] [2020-09-07 17:18:55.80 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789022}) ef28254a3ebf0bd6a7346138a3c27a90a165aee6f8c3176539b92979996a87f4 (BlockNo {unBlockNo = 4555189})) (Tip (SlotNo {unSlotNo = 7932827}) 93fb69de586d93662108eac490f26859eb0fd9ce858659f837d95563d83deb13 (BlockNo {unBlockNo = 4661463}))))) 200s 200s",String "ErrorPolicyTrace",String "18.156.143.30:3001"]
cardano-node_1              | [83e47172:cardano.node.DnsSubscription:Error:488] [2020-09-07 17:18:55.89 UTC] [String "Application Exception: 54.93.82.235:3001 HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789022}) ef28254a3ebf0bd6a7346138a3c27a90a165aee6f8c3176539b92979996a87f4 (BlockNo {unBlockNo = 4555189})) (Tip (SlotNo {unSlotNo = 7932827}) 93fb69de586d93662108eac490f26859eb0fd9ce858659f837d95563d83deb13 (BlockNo {unBlockNo = 4661463}))",String "SubscriptionTrace",String "\"relays-new.cardano-mainnet.iohk.io\""]
cardano-node_1              | [83e47172:cardano.node.ErrorPolicy:Warning:71] [2020-09-07 17:18:55.89 UTC] [String "ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (HeaderError (At (Block {blockPointSlot = SlotNo {unSlotNo = 5789249}, blockPointHash = 68914f093daebff961def6df4830a21b2fffccec69442e8e6b780e51c40d5217})) (HeaderProtocolError (HardForkValidationErrFromEra S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = \"\\NUL\\NUL\\157\\185\\199\\189l\\210Y\\130\\175\\220\\248\\140\\242\\129\\&4!\\138\\193\\175\\235\\238c*h(\\\\\\187\\156Y3\\239\\204lYMF\\160\\239F.>S\\248\\193l\\CAN\\162\\181\\204\\147\\241\\EOT\\183\\182P{R`z\\200vM\"}) (0 % 1) (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 20), unActiveSlotLog = -512932943875505334261962382072846}))]})))) (Tip (SlotNo {unSlotNo = 5789022}) ef28254a3ebf0bd6a7346138a3c27a90a165aee6f8c3176539b92979996a87f4 (BlockNo {unBlockNo = 4555189})) (Tip (SlotNo {unSlotNo = 7932827}) 93fb69de586d93662108eac490f26859eb0fd9ce858659f837d95563d83deb13 (BlockNo {unBlockNo = 4661463}))))) 200s 200s",String "ErrorPolicyTrace",String "54.93.82.235:3001"]
```
 if i try to do any query on graphql explorer as example 

```
{ cardano { tip { number slotNo epoch { number } } } }
```
the result is 
```
{
  "errors": [
    {
      "message": "TypeError: Cannot read property '0' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cardano"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: TypeError: Cannot read property '0' of null",
            "    at Object.<anonymous> (/application/packages/api-cardano-db-hasura/dist/executableSchema.js:78:35)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/application/packages/api-cardano-db-hasura/dist/executableSchema.js:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

My machine is macbook pro, system info `Darwin LONLAP10019MAC.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

And just run the command specified on the docs 
```
docker-compose up -d --build && docker-compose logs -f
```

**Comment by rhyslbw** [comment]
@acewf Are you running from the `master` branch or the latest release? If the former and you're ok with running unreleased software, please pull the latest commits as you are hitting a known issue with `cardano-node` that's not present in the version staged in `master`. Please ensure you [rebuild the db](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db)

**Comment by acewf** [comment]
Hi @rhyslbw yep i am running from master and pulled latest versions yesterday.
Sure will try to rebuild the db.. and check if it works.

Thanks

**Comment by acewf** [comment]
So @rhyslbw running from master, dropped the volume cardano-graphql_postgres-data still get the same results!
Last slot sync was 

```
cardano-db-sync-extended_1  | [db-sync-node:Info:38] [2020-09-08 19:15:36.94 UTC] insertShelleyBlock: epoch 210, slot 5785000, block 4554994, hash 49d90726c733f8b0569c9f52bfd862477e38f31a84ec68fa72ff181590595da6
```

Also looking into how rebuild the DB couldn't understand where (in what context) to run the command `cgql docker rebuild-service`, tried to find this command inside the containers but no luck.

I guess documentation needs to be more clear.
Maybe i will try to get another machine to test this out, but point of using docker is OS shouldn't matter.

**Comment by rhyslbw** [comment]
@acewf I've reviewed your logs again, and suspect also dropping the node data volume and rebuilding will resolve this. I would wait for the next release though, which is due for release over the next few days. This version will be targeting a new version of `cardano-db-sync` and will require a rebuild, plus `cardano-node@1.19.1`

**Comment by acewf** [comment]
Hi @rhyslbw thanks for the update, so i will wait on next release and hopefully get a working version.
