### ISSUE TITLE
Cannot set headers after they are sent to the client error

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/cardano-graphql#303]
### Issue

* cardano-graphql outputs the following error to journald logs, with a new error occurring about every 10 seconds, which matches the scrape frequency of the metrics endpoint:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/response.js:170:12)
    at /nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/packages/server/dist/apollo_server_plugins/prometheus_metrics_plugin.js:7:41
    at Layer.handle [as handle_request] (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/router/layer.js:95:5)
    at /nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/nix/store/7s7jvicimzxv0z1mk4nnm1ns8n75zz8q-cardano-graphql-2.0.0/node_modules/express/lib/router/index.js:335:12)
```

* The metrics exporter endpoint is now returning `Forbidden`.  Executing a curl to this endpoint causes the above error to occur

```
# curl http://127.0.0.1:3100/graphql
Forbidden
```

### Environment

**Git revision:**
cardano-graphql repo, master branch, commit: 81931202a17cd779955e9343ef1f52886596d59d

#### Platform

- [*] Linux / Other: NixOS 20.03

#### Runtime

- [*] Node.js

### Steps to reproduce the bug

* Run the nixos cardano-graphql service with the config found in the explorer role at https://github.com/input-output-hk/cardano-ops/blob/failsafe-recovery/roles/explorer.nix#L46-L52

### What is the expected behavior?

* The metrics endpoint to not return forbidden and log a "Cannot set headers after they are sent to the client" error

**Comment by rhyslbw** [comment]
```console
# curl http://127.0.0.1:3100/graphql
Forbidden
```
... is expected, I think you mean
``` console
# curl http://127.0.0.1:3100/metrics
Forbidden
```
