### ISSUE TITLE
Using master branch and DB rebuild can't startup.

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#335]
### Environment
{ os:
   { arch: 'x64',
     cpus:
      { count: 4, model: 'Westmere E56xx/L56xx/X56xx (Nehalem-C)' },
     release: '5.4.0-48-generic',
     totalMem: 4124917760,
     type: 'Linux' },
  version: '2.2.0' }

#### Platform

- [x ] Linux / Ubuntu
- [ ] Linux / Other
- [x ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [x ] Docker

**Runtime version**: 
```console
node -v: v10.19.0
docker version: Docker version 19.03.13, build 4484c46d9d
```

### Steps to reproduce the bug
Rebuild the DB either using the CLI NPM tool or manually removing the cardano-graphql_postgres-data volume.

### What is the expected behavior?
The postgres DB should start up.

### More details ###

I've set an .env file to override these values for the docker build:

CARDANO_DB_SYNC_VERSION=master
CARDANO_GRAPHQL_VERSION=master
CARDANO_NODE_VERSION=1.20.0

I've then cleared the cardano-graphql_postgres-data volume and started up. GraphQL isn't contactable and it appears that postgres isn't starting up. Here's the logs from the startup:

```
Creating cardano-graphql_postgres_1        ... done
Creating cardano-graphql_cardano-graphql_1          ... done
Creating cardano-graphql_cardano-node_1    ... done
Creating cardano-graphql_hasura_1                   ... done
Creating cardano-graphql_cardano-db-sync-extended_1 ... done
Attaching to cardano-graphql_cardano-db-sync-extended_1, cardano-graphql_hasura_1, cardano-graphql_cardano-node_1, cardano-graphql_postgres_1, cardano-graphql_cardano-graphql_1
cardano-graphql_1           | DbClient.pgSubscriber: Connected
cardano-graphql_1           | FetchError: request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.28.0.6:8080
cardano-graphql_1           |     at ClientRequest.<anonymous> (/application/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1455:11)
cardano-graphql_1           |     at ClientRequest.emit (events.js:223:5)
cardano-graphql_1           |     at Socket.socketErrorListener (_http_client.js:415:9)
cardano-graphql_1           |     at Socket.emit (events.js:223:5)
cardano-graphql_1           |     at emitErrorNT (internal/streams/destroy.js:92:8)
cardano-graphql_1           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
cardano-graphql_1           |     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
cardano-graphql_1           |   message: 'request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.28.0.6:8080',
cardano-graphql_1           |   type: 'system',
cardano-graphql_1           |   errno: 'ECONNREFUSED',
cardano-graphql_1           |   code: 'ECONNREFUSED'
cardano-graphql_1           | }
cardano-graphql_1           | request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.28.0.6:8080
cardano-graphql_1           | Fetching Hasura schema via introspection: Attempt 1 of 10, retrying...
cardano-graphql_1           | Fetching Hasura schema via introspection: Attempt 2 of 10, retrying...
cardano-graphql_1           | FetchError: request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.28.0.6:8080
cardano-graphql_1           |     at ClientRequest.<anonymous> (/application/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1455:11)
cardano-graphql_1           |     at ClientRequest.emit (events.js:223:5)
cardano-graphql_1           |     at Socket.socketErrorListener (_http_client.js:415:9)
cardano-graphql_1           |     at Socket.emit (events.js:223:5)
cardano-graphql_1           |     at emitErrorNT (internal/streams/destroy.js:92:8)
cardano-graphql_1           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
cardano-graphql_1           |     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
cardano-graphql_1           |   message: 'request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.28.0.6:8080',
cardano-graphql_1           |   type: 'system',
cardano-graphql_1           |   errno: 'ECONNREFUSED',
cardano-graphql_1           |   code: 'ECONNREFUSED'
cardano-graphql_1           | }
cardano-graphql_1           | request to http://hasura:8080/v1/graphql failed, reason: connect ECONNREFUSED 172.28.0.6:8080
cardano-node_1              | Listening on http://127.0.0.1:12798
cardano-node_1              | [3ef5dca6:cardano.node.release:Notice:5] [2020-10-08 21:53:44.67 UTC] CardanoProtocol
cardano-node_1              | [3ef5dca6:cardano.node.networkMagic:Notice:5] [2020-10-08 21:53:44.67 UTC] NetworkMagic 764824073
cardano-node_1              | [3ef5dca6:cardano.node.version:Notice:5] [2020-10-08 21:53:44.67 UTC] 1.20.0
cardano-node_1              | [3ef5dca6:cardano.node.commit:Notice:5] [2020-10-08 21:53:44.67 UTC] 1f2f51164b53b9b775c03ac9f1e23e7b70c74b05
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":false,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
postgres_1                  | 2020-10-08 21:53:43.703 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1                  | 2020-10-08 21:53:43.703 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1                  | 2020-10-08 21:53:43.723 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1                  | 2020-10-08 21:53:43.763 UTC [18] LOG:  database system was shut down at 2020-10-08 21:53:30 UTC
postgres_1                  | 2020-10-08 21:53:43.773 UTC [1] LOG:  database system is ready to accept connections
cardano-db-sync-extended_1  | /run/secrets
cardano-db-sync-extended_1  | Generating PGPASS file
cardano-db-sync-extended_1  | Connecting to network specified in configuration.yaml
cardano-db-sync-extended_1  | Missing: --state-dir FILEPATH
cardano-db-sync-extended_1  | 
cardano-db-sync-extended_1  | Usage: cardano-db-sync-extended --config FILEPATH --socket-path FILEPATH
cardano-db-sync-extended_1  |                                 --state-dir FILEPATH --schema-dir FILEPATH 
cardano-db-sync-extended_1  |                                 [--rollback-to-slot WORD]
cardano-db-sync-extended_1  |   Extended Cardano POstgreSQL sync node.
cardano-db-sync-extended_1  | Connecting to network specified in configuration.yaml
cardano-db-sync-extended_1  | Missing: --state-dir FILEPATH
cardano-db-sync-extended_1  | 
cardano-db-sync-extended_1  | Usage: cardano-db-sync-extended --config FILEPATH --socket-path FILEPATH
cardano-db-sync-extended_1  |                                 --state-dir FILEPATH --schema-dir FILEPATH 
cardano-db-sync-extended_1  |                                 [--rollback-to-slot WORD]
cardano-db-sync-extended_1  |   Extended Cardano POstgreSQL sync node.
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/cexplorer"}}}
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"db_migrate","info":"Already at the latest catalog version (34); nothing to do."}}
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 19","instance_id":"5b0d9578-7f74-4712-9670-84b174dfb290","message":"listener thread started"}}}
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 20","instance_id":"5b0d9578-7f74-4712-9670-84b174dfb290","message":"processor thread started"}}}
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"event_triggers","info":"preparing data"}}
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}}
hasura_1                    | {"type":"startup","timestamp":"2020-10-08T21:53:45.527+0000","level":"info","detail":{"kind":"server","info":{"time_taken":0.307401145,"message":"starting API server"}}}
cardano-graphql_cardano-db-sync-extended_1 exited with code 1
cardano-graphql_1           | Remote schema is missing Block
cardano-graphql_1           | Fetching Hasura schema via introspection: Attempt 3 of 10, retrying...
```

This environment is a direct clone from a running version that's using the default docker-compose without a DB rebuild. When the working environment starts up, it doesn't throw "Missing: --state-dir FILEPATH". I've let the broken environment run all night just to make sure and it's looping over the same errors.

**Comment by rhyslbw** [comment]
> it appears that postgres isn't starting up

It's starting:
```
postgres_1                  | 2020-10-08 21:53:43.773 UTC [1] LOG:  database system is ready to accept connections
```
... the error is from `cardano-db-sync-extended_1`, which is expected since you're overriding the supported version with `master`, which in this case has a breaking change. There will be a release next week
