### ISSUE TITLE
GraphQL error: database query error

### ISSUE THREAD

**Issue by PegasusPool** [input-output-hk/cardano-graphql#406]
### Environment

Mainnet

#### Platform

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

Ubuntu 20.04

#### Runtime

- [ ] Node.js
- [x] Docker

**Runtime version**: 
```console
docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

### Steps to reproduce the bug

1. git clone https://github.com/input-output-hk/cardano-graphql.git
2. checkout 3.1.1
3. docker-compose up -d --build && docker-compose logs -f
4. After some time the initial syncing begins and the graphql playground is available at http://localhost:3100/graphql
5. Execute the following query to get cardano-db-sync sync progress: `{ cardanoDbMeta { initialized syncPercentage }}`
6. Notice error response:
```
{
  "errors": [
    {
      "message": "GraphQL error: database query error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cardanoDbMeta"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "graphQLErrors": [
            {
              "extensions": {
                "path": "$",
                "code": "unexpected"
              },
              "message": "database query error"
            }
          ],
          "networkError": null,
          "message": "GraphQL error: database query error",
          "stacktrace": [
            "Error: GraphQL error: database query error",
            "    at new ApolloError (/application/node_modules/apollo-client/bundle.umd.js:92:26)",
            "    at /application/node_modules/apollo-client/bundle.umd.js:1588:34",
            "    at /application/node_modules/apollo-client/bundle.umd.js:2008:15",
            "    at Set.forEach (<anonymous>)",
            "    at /application/node_modules/apollo-client/bundle.umd.js:2006:26",
            "    at Map.forEach (<anonymous>)",
            "    at QueryManager.broadcastQueries (/application/node_modules/apollo-client/bundle.umd.js:2004:20)",
            "    at /application/node_modules/apollo-client/bundle.umd.js:2131:19",
            "    at Object.next (/application/node_modules/zen-observable/lib/Observable.js:322:23)",
            "    at notifySubscription (/application/node_modules/zen-observable/lib/Observable.js:135:18)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

In addition when the above query is executed the following is logged in the console window:
```
hasura_1                    | {"type":"query-log","timestamp":"2021-01-18T12:02:00.513+0000","level":"info","detail":{"request_id":"f9b8a9d5-007c-456c-a174-ccf49bf20746","generated_sql":{"cardano":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_4_e\"  FROM  (SELECT  \"_3_root.or.tip\".\"tip\" AS \"tip\"       ) AS \"_4_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"Cardano\"  WHERE ('true')     ) AS \"_0_root.base\" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  \"_2_e\"  FROM  (SELECT  \"_1_root.or.tip.base\".\"forgedAt\" AS \"forgedAt\"       ) AS \"_2_e\"      ) ) AS \"tip\" FROM  (SELECT  *  FROM \"public\".\"Block\"  WHERE ((\"_0_root.base\".\"tipBlockNo\") = (\"number\"))     ) AS \"_1_root.or.tip.base\"      ) AS \"_3_root.or.tip\" ON ('true')     LIMIT 1 ) AS \"_5_root\"      "}},"query":{"variables":{},"query":"{\n  cardano {\n    tip {\n      forgedAt\n    }\n  }\n}\n"}}}
postgres_1                  | 2021-01-18 12:02:00.514 UTC [4822] ERROR:  relation "public.Cardano" does not exist at character 205
postgres_1                  | 2021-01-18 12:02:00.514 UTC [4822] STATEMENT:  SELECT  coalesce(json_agg("root" ), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_3_root.or.tip"."tip" AS "tip"       ) AS "_4_e"      ) ) AS "root" FROM  (SELECT  *  FROM "public"."Cardano"  WHERE ('true')     ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  "_2_e"  FROM  (SELECT  "_1_root.or.tip.base"."forgedAt" AS "forgedAt"       ) AS "_2_e"      ) ) AS "tip" FROM  (SELECT  *  FROM "public"."Block"  WHERE (("_0_root.base"."tipBlockNo") = ("number"))     ) AS "_1_root.or.tip.base"      ) AS "_3_root.or.tip" ON ('true')     LIMIT 1 ) AS "_5_root"      

hasura_1                    | {"type":"http-log","timestamp":"2021-01-18T12:02:00.513+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"cardano-graphql"},"error":{"internal":{"statement":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_4_e\"  FROM  (SELECT  \"_3_root.or.tip\".\"tip\" AS \"tip\"       ) AS \"_4_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"Cardano\"  WHERE ('true')     ) AS \"_0_root.base\" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  \"_2_e\"  FROM  (SELECT  \"_1_root.or.tip.base\".\"forgedAt\" AS \"forgedAt\"       ) AS \"_2_e\"      ) ) AS \"tip\" FROM  (SELECT  *  FROM \"public\".\"Block\"  WHERE ((\"_0_root.base\".\"tipBlockNo\") = (\"number\"))     ) AS \"_1_root.or.tip.base\"      ) AS \"_3_root.or.tip\" ON ('true')     LIMIT 1 ) AS \"_5_root\"      ","prepared":true,"error":{"exec_status":"FatalError","hint":null,"message":"relation \"public.Cardano\" does not exist","status_code":"42P01","description":null},"arguments":["(Oid 114,Just (\"{\\\"x-hasura-role\\\":\\\"cardano-graphql\\\"}\",Binary))"]},"path":"$","error":"database query error","code":"unexpected"},"request_id":"f9b8a9d5-007c-456c-a174-ccf49bf20746","response_size":1011,"query":{"variables":{},"query":"{\n  cardano {\n    tip {\n      forgedAt\n    }\n  }\n}\n"}},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.18.0.4","method":"POST","content_encoding":null}}}

```

### What is the expected behavior?

The query is successful:
```
{
  "data": {
    "cardanoDbMeta": {
      "initialized": true,
      "syncPercentage": 100
    }
  }
}
```

Note: The above query works at https://cardano-graphql-mainnet.daedalus-operations.com/

**Comment by PegasusPool** [comment]
A few restarts seem to have resolved the issue.

**Comment by PegasusPool** [comment]
Towards the end of the sync the issue came back. 
Last time I checked syncPercentage was about 99.1 and at epoch 208.
Now same error is returned when query is executed.

**Comment by PegasusPool** [comment]
Restarting the docker containers seem to fix the issue, but it looks to be a worthy thing to look into.

**Comment by lcgogo** [comment]
met the same problem, I use cardano-graphql-3.1.1

**Comment by lcgogo** [comment]
> Restarting the docker containers seem to fix the issue, but it looks to be a worthy thing to look into.

@PegasusPool Hi pegasus, 
After restart the container, the slotNo epoch always stopped at 
{"data":{"cardano":{"tip":{"number":4957777,"slotNo":13956800,"epoch":null}}}}

Do you meet the similar issue? 

I have checked the node logs, the chain is fulled synced.

cardano-node_1              | [c2933d5e:cardano.node.ChainDB:Notice:786] [2021-01-25 03:36:51.19 UTC] Chain extended, new tip: 0b3dc42084ce9e044afffd5980970e66813ee4c15e575ae6b24030054cd985cc at slot 19979520

**Comment by rhyslbw** [comment]
#248 fixes the `cardanoDbMeta` sync state results @lcgogo  please try this once it's merged to see if you get valid information.

``` json
{"data":{"cardano":{"tip":{"number":4957777,"slotNo":13956800,"epoch":null}}}}
```
There's a [guard](https://github.com/input-output-hk/cardano-graphql/blob/3.1.1/packages/api-cardano-db-hasura/src/executableSchema.ts#L97-L99) in place to catch this condition, so it's a little puzzling. What do the logs for `cardano-db-sync` say?

**Comment by rhyslbw** [comment]
Released in https://github.com/input-output-hk/cardano-graphql/releases/tag/3.2.0
