### ISSUE TITLE
query initialized syncPercentage got an error

### ISSUE THREAD

**Issue by hufengvia** [input-output-hk/cardano-graphql#482]
when I run:
```
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardanoDbMeta { initialized syncPercentage }}"}' http://localhost:3100/graphql
```

I got an error:
```
{
    "errors": [
        {
            "message": "Error: \ncardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)",
            "locations": [
                {
                    "line": 1,
                    "column": 3
                }
            ],
            "path": [
                "cardanoDbMeta"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: Error: ",
                        "cardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)",
                        "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:168:35)",
                        "    at Generator.throw (<anonymous>)",
                        "    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

**Comment by rhyslbw** [comment]
That error is indicates the stack was probably not started to the point where `cardano-node` creates the socket mentioned here. 

_Apologies for the delay in response._ If you need further support please let me know
