### ISSUE TITLE
Error executing `docker-compose up -d --build && docker-compose logs -f`

### ISSUE THREAD

**Issue by Josema** [input-output-hk/cardano-graphql#508]
I'd like to use the cardano-node from Daedalus. But there is not docs about how to do this.

### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
v4.0.0

**Alternatively, what release or Git revision are you using:**

#### Platform

- [ ] Linux / Ubuntu

**Platform version**: 

Windows Subsystem Linux

#### Runtime

- [ ] Node.js
- [ ] Docker

**Runtime version**: 
```console
$ node -v
v14.15.4
$ docker -v
Docker version 20.10.7, build f0df350
$ docker-compose -v
docker-compose version 1.29.2, build 5becea4c
```

### Steps to reproduce the bug
```
$ docker-compose up -d --build && docker-compose logs -f
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by rhyslbw** [comment]
The error you provided indicates a problem with the Docker install, or that it's not running. This might help https://stackoverflow.com/questions/64633015/problem-launching-docker-compose-python-modules-not-installed
