### ISSUE TITLE
Error: \ncardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by ruttydm** [input-output-hk/cardano-graphql#529]
I just followed the instructions from the readme/guide and had the hasura docker image running for 2 days.
Suddenly the api stopped working with the following error:

Error: \ncardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)

I had to down the  docker image and up it again.

**Comment by zxpectre** [comment]
Having the same issue, not quite sure how to prove it yet but currently to use any known public cardano-graphql servers online, plus deploying my own seems imposible, too much random errors. 

For example using 4.0.0 --no-build on my own I'm getting:

```
{
  "errors": [
    {
      "message": "Error: \ncardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cardanoDbMeta"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Error: ",
            "cardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:168:35)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Maybe is totally unrelated but just in cases:
In other servers this last 48hs most of times I encounter errors on queries, like 
```
{
  "errors": [
    {
      "message": "database query error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "assets"
      ],
      "extensions": {
        "path": "$",
        "code": "unexpected",
        "exception": {
          "message": "database query error",
          "stacktrace": [
            "GraphQLError: database query error",
            "    at Object.relocatedError (/app/node_modules/@graphql-tools/utils/index.cjs.js:3350:12)",
            "    at handleNull (/app/node_modules/@graphql-tools/delegate/index.cjs.js:744:49)",
            "    at handleResult (/app/node_modules/@graphql-tools/delegate/index.cjs.js:1007:16)",
            "    at checkResultAndHandleErrors (/app/node_modules/@graphql-tools/delegate/index.cjs.js:1036:12)",
            "    at CheckResultAndHandleErrors.transformResult (/app/node_modules/@graphql-tools/delegate/index.cjs.js:1030:16)",
            "    at /app/node_modules/@graphql-tools/delegate/index.cjs.js:1187:40",
            "    at Array.reduceRight (<anonymous>)",
            "    at Transformer.transformResult (/app/node_modules/@graphql-tools/delegate/index.cjs.js:1186:37)",
            "    at /app/node_modules/@graphql-tools/delegate/index.cjs.js:1290:71",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
or 
```
{
    "errors": [
        {
            "message": "TypeError: Cannot read property 'currentEpoch' of undefined",
            "locations": [
                {
                    "line": 94,
                    "column": 3
                }
            ],
            "path": [
                "cardano"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: TypeError: Cannot read property 'currentEpoch' of undefined",
                        "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:159:35)",
                        "    at Generator.next (<anonymous>)",
                        "    at fulfilled (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:5:58)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```
(this last one makes me dubt if my queries are right, but as i said, everyting start happening this las 48hs aprox.)

Also queries with assets fail weirdly for the first 20 minutes aprox, on new transactions, or new minting transactions.

Too much to report, but hope this make sense. I really want to rely on this server to build stuff, but sometimes it gets really hard to rely on. Any help would be apretiated. Thnks!

**Comment by rhyslbw** [comment]
The next version resolves the issues surrounding assets and the cardano-node socket. You can test this out by building the `master` branch, making sure to re-initialise the git submodules.

**Comment by rhyslbw** [comment]
The release branch has been made, and we'll be tagging once final QA checks are performed: 
https://github.com/input-output-hk/cardano-graphql/tree/5-0-stable
