### ISSUE TITLE
5.0.0 failing to init with hasura for "Cannot read property 'protocolVersion' of null"

### ISSUE THREAD

**Issue by jun0tpyrc** [input-output-hk/cardano-graphql#573]
inputoutput/cardano-node: 1.27.0 <- `working` , e.g. for testnet keep ingesting
```
[de3f110d:cardano.node.ChainDB:Notice:104] [2021-08-14 12:31:52.46 UTC] Chain extended, new tip: d2878b14216cd0c60b4632e4f181a25b608502099dca87cf07008f5b62cdfb32 at slot 34575096
```
inputoutput/cardano-db-sync: 10.0.1  <- `working`, sync head slot to db too
```
[db-sync-node:Info:81116] [2021-08-14 12:33:50.21 UTC] insertShelleyBlock(Mary): epoch 150, slot 34575214, block 2831653, hash 3309be836275a77b2455d193d902a7749029c132e05ce7a8a5b1a3612d748212
```

inputoutput/cardano-graphql-hasura:5.0.0 <-  `graphql<->hasura url working`, because it's printing some output for query from graphql component 
```
{"type":"http-log","timestamp":"2021-08-14T12:34:04.600+0000","level":"info","detail":{"operation":{"query_execution_time":1.349269e-3,"user_vars":{"x-hasura-role":"cardano-graphql"},"request_id":"1ca94bbe-53ab-49a5-8ca9-d09f7153c100","response_size":89,"request_read_time":5.682e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.25.0.3","method":"POST","content_encoding":"gzip"}}}
{"type":"query-log","timestamp":"2021-08-14T12:34:05.635+0000","level":"info","detail":{"request_id":"a5847f93-6d8a-40a4-af75-6ebff41d1880","generated_sql":{"cardano":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_7_e\"  FROM  (SELECT  \"_6_root.or.currentEpoch\".\"currentEpoch\" AS \"currentEpoch\"       ) AS \"_7_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"Cardano\"  WHERE ('true')     ) AS \"_0_root.base\" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  \"_5_e\"  FROM  (SELECT  \"_4_root.or.currentEpoch.or.adaPots\".\"adaPots\" AS \"adaPots\"       ) AS \"_5_e\"      ) ) AS \"currentEpoch\" FROM  (SELECT  *  FROM \"public\".\"Epoch\"  WHERE ((\"_0_root.base\".\"currentEpochNo\") = (\"number\"))     ) AS \"_1_root.or.currentEpoch.base\" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  \"_3_e\"  FROM  (SELECT  \"_2_root.or.currentEpoch.or.adaPots.base\".\"reserves\" AS \"reserves\"       ) AS \"_3_e\"      ) ) AS \"adaPots\" FROM  (SELECT  *  FROM \"public\".\"AdaPots\"  WHERE ((\"_1_root.or.currentEpoch.base\".\"number\") = (\"epochNo\"))     ) AS \"_2_root.or.currentEpoch.or.adaPots.base\"      ) AS \"_4_root.or.currentEpoch.or.adaPots\" ON ('true')      ) AS \"_6_root.or.currentEpoch\" ON ('true')     LIMIT 1 ) AS \"_8_root\"      "},"withdrawals_aggregate":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  json_build_object('aggregate', json_build_object('sum', json_build_object('amount', sum(\"amount\" ) ) ) ) AS \"root\" FROM  (SELECT  \"_0_root.base\".\"amount\" AS \"amount\" FROM  (SELECT  *  FROM \"public\".\"Withdrawal\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_1_root\"      "},"utxos_aggregate":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  json_build_object('aggregate', json_build_object('sum', json_build_object('value', sum(\"value\" ) ) ) ) AS \"root\" FROM  (SELECT  \"_0_root.base\".\"value\" AS \"value\" FROM  (SELECT  *  FROM \"public\".\"Utxo\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_1_root\"      "},"rewards_aggregate":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  json_build_object('aggregate', json_build_object('sum', json_build_object('amount', sum(\"amount\" ) ) ) ) AS \"root\" FROM  (SELECT  \"_0_root.base\".\"amount\" AS \"amount\" FROM  (SELECT  *  FROM \"public\".\"Reward\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_1_root\"      "}},"query":{"query":"query {\n          cardano {\n              currentEpoch {\n                  adaPots {\n                      reserves\n                  }\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}}
{"type":"http-log","timestamp":"2021-08-14T12:34:06.822+0000","level":"info","detail":{"operation":{"query_execution_time":1.187458201,"user_vars":{"x-hasura-role":"cardano-graphql"},"request_id":"a5847f93-6d8a-40a4-af75-6ebff41d1880","response_size":190,"request_read_time":6.078e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.25.0.3","method":"POST","content_encoding":"gzip"}}}
```

inputoutput/cardano-graphql:5.0.0 <- fail,  looping for `Cannot read property 'protocolVersion' ` ,never finish
```
{"name":"cardano-graphql","hostname":"f532e2a26a56","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-08-13T12:30:14.509Z","v":0}
{"name":"cardano-graphql","hostname":"f532e2a26a56","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2021-08-13T12:30:20.283Z","v":0}
{"name":"cardano-graphql","hostname":"f532e2a26a56","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2021-08-13T12:30:20.284Z","v":0}
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'protocolVersion' of null
    at HasuraClient.<anonymous> (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:277:99)
    at Generator.next (<anonymous>)
    at fulfilled (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: Error: currentEpoch is only available when close to the chain tip. This is expected during the initial chain-sync.
    at HasuraClient.<anonymous> (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:113:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
{"name":"cardano-graphql","hostname":"f532e2a26a56","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2021-08-14T12:03:42.062Z","v":0}
{"name":"cardano-graphql","hostname":"f532e2a26a56","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-08-14T12:03:42.344Z","v":0}
```

**Comment by jun0tpyrc** [comment]
not being pgsql problem , i pruned whole directory to start db_sync 10.0.1 with testnet & mainnet, seeing the same thing

**Comment by rhyslbw** [comment]
This is resolved in the upcoming version, which is currently in beta. The beta status reflects the potential for there to be changes to the API or DB schema which may require another sync, but if you're stuck I'd suggest trying this version to see if it resolved the issue.

https://github.com/input-output-hk/cardano-graphql/releases/tag/5.1.0-beta.0

**Comment by jun0tpyrc** [comment]
it seems taking long time for the graphql `init` step , while we seeing keep sending query to hasura (running against db-sync that already at latest block) 

Any reference time that how long this is expected to take ?

```
{"name":"cardano-graphql","hostname":"6668403c58de","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-08-16T03:20:39.576Z","v":0}
{"name":"cardano-graphql","hostname":"6668403c58de","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2021-08-16T03:20:49.729Z","v":0}
{"name":"cardano-graphql","hostname":"6668403c58de","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2021-08-16T03:20:49.729Z","v":0}
```

```
{"type":"http-log","timestamp":"2021-08-16T04:12:51.037+0000","level":"info","detail":{"operation":{"query_execution_time":1.279246563,"user_vars":{"x-hasura-role":"cardano-graphql"},"request_id":"0007602c-13b9-449c-8ce8-08d3a1e2af77","response_size":179,"request_read_time":5.329e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.25.0.8","method":"POST","content_encoding":"gzip"}}}
{"type":"query-log","timestamp":"2021-08-16T04:13:49.758+0000","level":"info","detail":{"request_id":"56d4a71f-e905-4148-8f7e-70ce0e3dd1a0","generated_sql":{"withdrawals_aggregate":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  json_build_object('aggregate', json_build_object('sum', json_build_object('amount', sum(\"amount\" ) ) ) ) AS \"root\" FROM  (SELECT  \"_0_root.base\".\"amount\" AS \"amount\" FROM  (SELECT  *  FROM \"public\".\"Withdrawal\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_1_root\"      "},"utxos_aggregate":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  json_build_object('aggregate', json_build_object('sum', json_build_object('value', sum(\"value\" ) ) ) ) AS \"root\" FROM  (SELECT  \"_0_root.base\".\"value\" AS \"value\" FROM  (SELECT  *  FROM \"public\".\"Utxo\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_1_root\"      "},"rewards_aggregate":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  json_build_object('aggregate', json_build_object('sum', json_build_object('amount', sum(\"amount\" ) ) ) ) AS \"root\" FROM  (SELECT  \"_0_root.base\".\"amount\" AS \"amount\" FROM  (SELECT  *  FROM \"public\".\"Reward\"  WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_1_root\"      "},"epochs":{"prepared_arguments":["{\"x-hasura-role\":\"cardano-graphql\"}"],"query":"SELECT  coalesce(json_agg(\"root\" ORDER BY \"root.pg.number\" DESC NULLS FIRST), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_4_e\"  FROM  (SELECT  \"_3_root.or.adaPots\".\"adaPots\" AS \"adaPots\"       ) AS \"_4_e\"      ) ) AS \"root\", \"_0_root.base\".\"number\" AS \"root.pg.number\" FROM  (SELECT  *  FROM \"public\".\"Epoch\"  WHERE ('true')     ) AS \"_0_root.base\" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  \"_2_e\"  FROM  (SELECT  \"_1_root.or.adaPots.base\".\"reserves\" AS \"reserves\"       ) AS \"_2_e\"      ) ) AS \"adaPots\" FROM  (SELECT  *  FROM \"public\".\"AdaPots\"  WHERE ((\"_0_root.base\".\"number\") = (\"epochNo\"))     ) AS \"_1_root.or.adaPots.base\"      ) AS \"_3_root.or.adaPots\" ON ('true')    ORDER BY \"root.pg.number\" DESC NULLS FIRST LIMIT 1 ) AS \"_5_root\"      "}},"query":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              adaPots {\n                  reserves\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}}
{"type":"http-log","timestamp":"2021-08-16T04:13:51.080+0000","level":"info","detail":{"operation":{"query_execution_time":1.321322931,"user_vars":{"x-hasura-role":"cardano-graphql"},"request_id":"56d4a71f-e905-4148-8f7e-70ce0e3dd1a0","response_size":179,"request_read_time":5.466e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.25.0.8","method":"POST","content_encoding":"gzip"}}}
```

**Comment by rhyslbw** [comment]
Try restarting with more logging:

```
docker-compose down &&\
LOGGER_MIN_SEVERITY=debug docker-compose up -d &&\
docker-compose logs -f
```

You could also start a fresh instance of the _testnet_ stack using the command [here](https://github.com/input-output-hk/cardano-graphql#b-pull-and-run-via-docker-compose) to see if there's maybe an old volume causing problems. The _testnet_ node will sync is a lot less time.
