### ISSUE TITLE
submitTransaction WebSocketClosed: WebSocket is closed

### ISSUE THREAD

**Issue by hzccc** [input-output-hk/cardano-graphql#606]
### Environment
Environment set up with docker-compose. Version is 5.1.0.
When building and running, the environment variable NETWORK=mainnet is set.

#### Platform

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [x] Docker

**Runtime version**: 
```console
$ docker version

Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~20.04.1
  Built:            Wed Aug  4 19:07:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Steps to reproduce the bug
Execute this query
```graphql
mutation SubmitTransaction(
  $transaction: String!
) {
  submitTransaction(transaction: $transaction) {
    hash
  }
}
```
With this query parameter:

```json
{
    "transaction":"83a4008182582023960fad6cf29d99f774587d8cdd91f097e22dc14d16609ff038b4f2396b287300018282583901ed06b79162edc93f93f2b0ad1135c8980a2f839879c13be6fec3e47e799caf34f6d1558c14561f48bd0ca175298b306b8e79b2b1e0cead551a000186a082583901ed06b79162edc93f93f2b0ad1135c8980a2f839879c13be6fec3e47e799caf34f6d1558c14561f48bd0ca175298b306b8e79b2b1e0cead551a000c3500021a000186a0031a026ec993a1008182582049531603f3005e001a41e352945e6223e054ca6e8b1cb22b5c4a2233666501365840d5d5e2f2dc159d8699b428727f429e42dad2a087e6da7f50a05c22b946e91b9cc6c011ba595af62f57e2b22d060a955b224601fab738b1479ee8f6022d6ead0440"
}
```
and then request timeout..
graphql  returns this error：
```console
bunyan usage error: /app/node_modules/isomorphic-ws/node_modules/ws/lib/websocket.js:198: attempt to log with an unbound log method: `this` is: <ref *1> WebSocket {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _binaryType: 'nodebuffer',
  _closeCode: 1006,
  _closeFrameReceived: false,
  _closeFrameSent: false,
  _closeMessage: '',
  _closeTimer: null,
  _extensions: {},
  _protocol: '',
  _readyState: 3,
  _receiver: Receiver {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _extensions: {},
    _isServer: false,
    _maxPayload: 104857600,
    _bufferedBytes: 0,
    _buffers: [],
    _compressed: false,
    _payloadLength: 1,
    _mask: undefined,
    _fragmented: 0,
    _masked: false,
    _fin: true,
    _opcode: 9,
    _totalPayloadLength: 0,
    _messageLength: 0,
    _fragments: [],
    _state: 0,
    _loop: false,
    [Symbol(kCapture)]: false,
    [Symbol(websocket)]: [Circular *1]
  },
  _sender: Sender {
    _extensions: {},
    _socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'cardano-node-ogmios',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      write: [Function: writeAfterFIN],
      [Symbol(async_id_symbol)]: 356,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 147,
      [Symbol(kBytesWritten)]: 980,
      [Symbol(RequestTimeout)]: undefined,
      [Symbol(websocket)]: undefined
    },
    _firstFragment: true,
    _compress: false,
    _bufferedBytes: 0,
    _deflating: false,
    _queue: []
  },
  _socket: Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: 'cardano-node-ogmios',
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Function: onReadableStreamEnd],
      error: [Function: socketOnError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      errored: null,
      closed: true,
      closeEmitted: false,
      writable: true
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    parser: null,
    _httpMessage: null,
    timeout: 0,
    write: [Function: writeAfterFIN],
    [Symbol(async_id_symbol)]: 356,
    [Symbol(kHandle)]: null,
    [Symbol(kSetNoDelay)]: true,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 147,
    [Symbol(kBytesWritten)]: 980,
    [Symbol(RequestTimeout)]: undefined,
    [Symbol(websocket)]: undefined
  },
  _bufferedAmount: 0,
  _isServer: false,
  _redirects: 0,
  _url: 'ws://cardano-node-ogmios:1337',
  _req: null,
  [Symbol(kCapture)]: false
}
```
and then request again,returns this error:
```json
{
  "errors": [
    {
      "message": "WebSocketClosed: WebSocket is closed",
      "locations": [
        {
          "line": 1,
          "column": 54
        }
      ],
      "path": [
        "submitTransaction"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: WebSocketClosed: WebSocket is closed",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:77:43)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### What is the expected behavior?
I want to successfully broadcast a transaction and return hash

**Comment by rhyslbw** [comment]
Please provide a sample of the service logs from `cardano-node-ogmios`. Did you submit this shortly after starting the stack?

**Comment by hzccc** [comment]
> Please provide a sample of the service logs from `cardano-node-ogmios`. Did you submit this shortly after starting the stack?

> Did you submit this shortly after starting the stack?
`No`


cardano-node-ogmios has this information:
```console
{"severity":"Info","timestamp":"2021-09-23T07:49:59.116584343Z","thread":"1065434","message":{"tag":"OgmiosWebSocket","webSocket":{"userAgent":"User-Agent unknown","tag":"WebSocketConnectionEnded"}},"version":"v4.0.0"}
[d70b65f7:cardano.node.LocalErrorPolicy:Error:861] [2021-09-23 07:50:00.14 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 38> closed when reading data, waiting on next header True")
```
cardano-graphql has an error：
```console
bunyan usage error: /app/node_modules/isomorphic-ws/node_modules/ws/lib/websocket.js:198: attempt to log with an unbound log method: `this` is: <ref *1> WebSocket {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _binaryType: 'nodebuffer',
  _closeCode: 1006,
  _closeFrameReceived: false,
  _closeFrameSent: false,
  _closeMessage: '',
  _closeTimer: null,
  _extensions: {},
  _protocol: '',
  _readyState: 3,
  _receiver: Receiver {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _extensions: {},
    _isServer: false,
    _maxPayload: 104857600,
    _bufferedBytes: 0,
    _buffers: [],
    _compressed: false,
    _payloadLength: 1,
    _mask: undefined,
    _fragmented: 0,
    _masked: false,
    _fin: true,
    _opcode: 9,
    _totalPayloadLength: 0,
    _messageLength: 0,
    _fragments: [],
    _state: 0,
    _loop: false,
    [Symbol(kCapture)]: false,
    [Symbol(websocket)]: [Circular *1]
  },
  _sender: Sender {
    _extensions: {},
    _socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'cardano-node-ogmios',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      write: [Function: writeAfterFIN],
      [Symbol(async_id_symbol)]: 356,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 147,
      [Symbol(kBytesWritten)]: 980,
      [Symbol(RequestTimeout)]: undefined,
      [Symbol(websocket)]: undefined
    },
    _firstFragment: true,
    _compress: false,
    _bufferedBytes: 0,
    _deflating: false,
    _queue: []
  },
  _socket: Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: 'cardano-node-ogmios',
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Function: onReadableStreamEnd],
      error: [Function: socketOnError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      errored: null,
      closed: true,
      closeEmitted: false,
      writable: true
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    parser: null,
    _httpMessage: null,
    timeout: 0,
    write: [Function: writeAfterFIN],
    [Symbol(async_id_symbol)]: 356,
    [Symbol(kHandle)]: null,
    [Symbol(kSetNoDelay)]: true,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 147,
    [Symbol(kBytesWritten)]: 980,
    [Symbol(RequestTimeout)]: undefined,
    [Symbol(websocket)]: undefined
  },
  _bufferedAmount: 0,
  _isServer: false,
  _redirects: 0,
  _url: 'ws://cardano-node-ogmios:1337',
  _req: null,
  [Symbol(kCapture)]: false
}
```

**Comment by dingxiangfei2009** [comment]
@hzccc If you are still experiencing the same issue, would you mind hitting the HTTP endpoint on port 3001 of `cardano-node-ogmios`?

This service will not be listening on any exposed ports unless the `cardano-node` IPC socket is ready. You might need to wait and watch its log.

**Comment by hzccc** [comment]
> @hzccc If you are still experiencing the same issue, would you mind hitting the HTTP endpoint on port 3001 of `cardano-node-ogmios`?
> 
> This service will not be listening on any exposed port unless the `cardano-node` IPC socket is ready. You might need to wait and watch its log.

Where can I get the Ogmios HTTP API reference? I only saw the Websocket API reference

**Comment by rcmorano** [comment]
I got this exact same error (`"message": "WebSocketClosed: WebSocket is closed"`), and `ogmios`/`cardano-node` were correctly working.
It somehow lost connection to ogmios and it seems it doesn not try to reconnect until restart, because the problem was solved by just restarting `cardano-graphql`.

**Comment by sokiaoba** [comment]
I encounstered this error (`graphql: WebSocketClosed: WebSocket is closed`) in sending transaction.
Seemingly the problem occured temporarily and fixed by itself.

Our cardano node environment is something like this.

* cardano-db-sync:13.0.5
* cardano-graphql:7.0.2
* cardano-node:v1.35.3
* ogmios:v5.5.7
* cardano-graphql-hasura:7.0.1

Does anyone know the cause of it? 
I'm concerned about reproducibility of this. 

Thanks.
