### ISSUE TITLE
Can't perform query while syncing

### ISSUE THREAD

**Issue by ggcaponetto** [input-output-hk/cardano-graphql#640]
### Environment
Ubuntu 21, docker, cardano-graphql 6.0.0

Followed the [getting started](https://github.com/input-output-hk/cardano-graphql#getting-started) for the testnet.
Executed via curl the query to get the ``ìnitialized`` flag.

At this point I expected to get an output but instead I get:

``curl: (56) Recv failure: Connection reset by peer``

Logs of the cardano-graphql container:

```
root@cardano-testnet-vultr:~/code/cardano-graphql# {"name":"cardano-graphql","hostname":"1c3a95e73825","pid":1,"level":30,"module":"ChainFollower","msg":"Initializing","time":"2021-11-21T15:57:26.352Z","v":0}
(node:1) UnhandledPromiseRejectionWarning: Error: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              adaPots {\n                  reserves\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)
    at step (/app/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"name":"cardano-graphql","hostname":"1c3a95e73825","pid":1,"level":30,"module":"ChainFollower","msg":"Initialized","time":"2021-11-21T15:58:25.596Z","v":0}
```

Logs of the postgres container:

```
2021-11-21 16:05:08.274 UTC [31] ERROR:  relation "public.Block" does not exist at character 862
2021-11-21 16:05:08.274 UTC [31] STATEMENT:  SELECT  coalesce(json_agg("root" ORDER BY "root.or.firstAppearedInBlock.pg.slotNo" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  "_3_root.or.firstAppearedInBlock"."root.or.firstAppearedInBlock.pg.slotNo" AS "root.or.firstAppearedInBlock.pg.slotNo", row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_3_root.or.firstAppearedInBlock"."firstAppearedInBlock" AS "firstAppearedInBlock"       ) AS "_4_e"      ) ) AS "root" FROM  (SELECT  *  FROM "public"."Asset"  WHERE ('true')     ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  "_1_root.or.firstAppearedInBlock.base"."slotNo" AS "root.or.firstAppearedInBlock.pg.slotNo", row_to_json((SELECT  "_2_e"  FROM  (SELECT  "_1_root.or.firstAppearedInBlock.base"."hash" AS "hash", "_1_root.or.firstAppearedInBlock.base"."slotNo" AS "slotNo"       ) AS "_2_e"      ) ) AS "firstAppearedInBlock" FROM  (SELECT  *  FROM "public"."Block"  WHERE (("_0_root.base"."firstAppearedInSlot") = ("slotNo"))     ) AS "_1_root.or.firstAppearedInBlock.base"      ) AS "_3_root.or.firstAppearedInBlock" ON ('true')    ORDER BY "root.or.firstAppearedInBlock.pg.slotNo" DESC NULLS FIRST LIMIT 1 OFFSET ('1')::integer) AS "_5_root"
root@cardano-testnet-vultr:~/code/cardano-graphql#
```

**Comment by CyberCyclone** [comment]
It's expected that you won't be able to query while it's syncing. After about 18+ hours trying bringing the stack down and back up again and GraphQL should be alive. GraphQL depends on the other services to be running before it comes online.

**Comment by ggcaponetto** [comment]
I solved by the following steps:

1. pull and run via docker with snapshot restoring
2. restart all services
3. wait for the node to catch up with the current tip
4. restart all the services
5. run the query via curl

@CyberCyclone  thanks.
