### ISSUE TITLE
Query for block reports INTERNAL_SERVER_ERROR to browser

### ISSUE THREAD

**Issue by njd42** [input-output-hk/cardano-graphql#659]
After querying various blocks (they happen to have plutus scripts in them - but that may not be the cause) the browser returns:

SORRY, WE COULD NOT FIND ANY RESULTS MATCHING:
9635fd19af660a4f7db984499cd3097304d43e79f7589cb7ca81a777454f104d

for blocks, ones that - a few moments earlier - it was able to show.

The browser JS console has the following contents that may help isolate the issue:

> Uncaught (in promise) Error: Cannot return null for non-nullable field Token.asset.: {"response":{"errors":[{"message":"Cannot return null for non-nullable field Token.asset.","locations":[{"line":57,"column":5}],"path":["blocks",0,"transactions",0,"mint",0,"asset"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return null for non-nullable field Token.asset.","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:560:13)","    at completeValueCatchingError (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:495:19)","    at resolveField (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:435:10)","    at executeFields (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:591:12)","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:557:21)","    at completeValueCatchingError (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:495:19)","    at /nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:618:25"]}}},{"message":"Cannot return null for non-nullable field Token.asset.","locations":[{"line":57,"column":5}],"path":["blocks",0,"transactions",1,"mint",0,"asset"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return null for non-nullable field Token.asset.","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:560:13)","    at completeValueCatchingError (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:495:19)","    at resolveField (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:435:10)","    at executeFields (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:591:12)","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:557:21)","    at completeValueCatchingError (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:495:19)","    at /nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:618:25"]}}},{"message":"Cannot return null for non-nullable field Token.asset.","locations":[{"line":57,"column":5}],"path":["blocks",0,"transactions",2,"mint",0,"asset"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return null for non-nullable field Token.asset.","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:560:13)","    at completeValueCatchingError (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:495:19)","    at resolveField (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:435:10)","    at executeFields (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:591:12)","    at completeValue (/nix/store/iyhi9v4xg9xzijx8lvrkp0cn9kch0l7y-cardano-graphql-6.1.0/node_modules/graphql/execution/execute.js:557:21)","    at comple    at e.<anonymous>

It may be that the URL https://explorer.cardano.org/en/block?id=7e147a6ed3461d7f787eff98b495ab16313a989e95ba4fa4de103791e4531616 is sufficient to invoke this issue

**Comment by CyberCyclone** [comment]
Are you saying that you were able to query them with no issues and then it later fails?

Can you please post the entire query?

My guess is that if the block was a few seconds old, it could have been removed by the chain due to the network choosing the other fork which doesn't include this block.
