### ISSUE TITLE
graphql server cann't start after sync.

### ISSUE THREAD

**Issue by somereason** [input-output-hk/cardano-graphql#701]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```

```
{
  os: {
    arch: 'x64',
    cpus: {
      count: 4,
      model: 'Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz'
    },
    release: '5.11.0-1022-aws',
    totalMem: 16586838016,
    type: 'Linux'
  },
  version: '6.2.0'
}
```

**Alternatively, what release or Git revision are you using:**

#### Platform

- [*] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [*] Docker

**Runtime version**: 
```console
node -v
docker version
```

ubuntu@ip-172-31-35-74:~/cardano-graphql$ node -v
v17.8.0
ubuntu@ip-172-31-35-74:~/cardano-graphql$ docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
ubuntu@ip-172-31-35-74:~/cardano-graphql$ 

### Steps to reproduce the bug

start commend: 

```bash
export NETWORK=testnet &&docker pull inputoutput/cardano-graphql:6.2.0-${NETWORK} &&docker pull inputoutput/cardano-graphql-hasura:6.2.0 &&docker pull cardanosolutions/cardano-node-ogmios:v5.1.0-${NETWORK} &&RESTORE_SNAPSHOT=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/12/db-sync-snapshot-schema-12-block-3429999-x86_64.tgz API_PORT=3101 HASURA_PORT=8091 OGMIOS_PORT=1338 POSTGRES_PORT=5433 docker-compose -p ${NETWORK} up -d &&docker-compose -p ${NETWORK} logs -f
```

at first It works, but commend ```{ cardanoDbMeta { initialized syncPercentage }}``` doesn't work. error message is 
```
{
  "errors": [
    {
      "message": "QueryUnavailableInCurrentEra. ledgerTip",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cardanoDbMeta"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: QueryUnavailableInCurrentEra. ledgerTip",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:233:39)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

After 10 hours. according to logs of ogmios, sync has finished. 
```
cardano-node-ogmios_1       | {"severity":"Info","timestamp":"2022-04-01T03:20:22.611562039Z","thread":"17","message":{"Health":{"tag":"HealthTick","status":{"startTime":"2022-03-31T17:22:27.341678066Z","lastKnownTip":{"slot":54414006,"hash":"49d4bd76c43dce8df544b12f69112986418363a122f27e2377b13a2590baa4b3","blockNo":3440363},"lastTipUpdate":"2022-04-01T03:20:22.611384053Z","networkSynchronization":0.99999,"currentEra":"Alonzo","metrics":{"sessionDurations":{"max":0,"min":0,"mean":31772200},"totalMessages":3,"runtimeStats":{"currentHeapSize":716,"maxHeapSize":1027,"gcCpuTime":55249311361,"cpuTime":1008211026082},"activeConnections":0,"totalUnrouted":0,"totalConnections":3},"connectionStatus":"connected","currentEpoch":196,"slotInEpoch":111606}}},"version":"v5.1.0"}

```

but graphql server still cann't start( It might have restarted due to database schema change). 

```
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":50,"err":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"172.18.0.4","port":5432},"msg":"connect ECONNREFUSED 172.18.0.4:5432","time":"2022-03-31T17:22:29.157Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 1","time":"2022-03-31T17:22:29.160Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 2","time":"2022-03-31T17:22:29.662Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 3","time":"2022-03-31T17:22:30.165Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 4","time":"2022-03-31T17:22:30.669Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 5","time":"2022-03-31T17:22:31.171Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 6","time":"2022-03-31T17:22:31.673Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":50,"module":"Db","err":{},"msg":"pgSubscriber","time":"2022-03-31T17:22:32.176Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2022-03-31T17:22:35.803Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2022-03-31T17:22:36.180Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2022-03-31T17:26:31.440Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2022-03-31T17:26:31.440Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initialized","time":"2022-03-31T17:26:31.456Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"MetadataFetchClient","msg":"Initializing","time":"2022-03-31T17:26:31.457Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":50,"msg":"Cannot read property 'status' of undefined","time":"2022-03-31T17:28:42.066Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: cardano-db-sync-extended starting, schema will be reset","time":"2022-03-31T17:42:55.045Z","v":0}
cardano-graphql_1           | (node:1) UnhandledPromiseRejectionWarning: Error: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              adaPots {\n                  reserves\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}
cardano-graphql_1           |     at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)
cardano-graphql_1           |     at step (/app/node_modules/graphql-request/dist/index.js:63:23)
cardano-graphql_1           |     at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)
cardano-graphql_1           |     at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)
cardano-graphql_1           |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
cardano-graphql_1           | (Use `node --trace-warnings ...` to show where the warning was created)
cardano-graphql_1           | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
cardano-graphql_1           | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"ChainFollower","msg":"Initializing","time":"2022-03-31T17:42:55.542Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"ChainFollower","msg":"Initialized","time":"2022-03-31T17:42:55.549Z","v":0}
```

after I restart graphql by ```docker-compose restart cardano-graphql```, server still cannot start. log is: 

```
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2022-04-01T02:21:34.168Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"3cd5cb7b645e","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2022-04-01T02:21:34.480Z","v":0}
```

At the same time, postgresql use 100% cpu of one core. the sql running is 
```sql
DELETE FROM "block" WHERE "id"=2 

```

### What is the expected behavior?

Cardano graphql run normally.

**Comment by rhyslbw** [comment]
Do you know how far along the `cardano-node` sync is?

**Comment by somereason** [comment]
> Do you know how far along the `cardano-node` sync is?

docker container includes: 
```
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED       STATUS                 PORTS                                                                       NAMES
d40bd92b12a9   inputoutput/cardano-db-sync:12.0.0                    "/nix/store/5ghw8rqx…"   2 hours ago   Up 2 hours                                                                                         testnet_cardano-db-sync-extended_1
0c319851bdf9   inputoutput/cardano-graphql-hasura:6.2.0              "docker-entrypoint.s…"   2 hours ago   Up 2 hours             0.0.0.0:8091->8080/tcp, :::8091->8080/tcp                                   testnet_hasura_1
0eb2c2c6174e   inputoutput/cardano-graphql:6.2.0-testnet             "node index.js"          2 hours ago   Up 2 hours             3101/tcp, 0.0.0.0:3101->3100/tcp, :::3101->3100/tcp                         testnet_cardano-graphql_1
cd65224a24dc   cardanosolutions/cardano-node-ogmios:v5.1.0-testnet   "/root/cardano-node-…"   2 hours ago   Up 2 hours (healthy)   3000/tcp, 12788/tcp, 12798/tcp, 0.0.0.0:1338->1337/tcp, :::1338->1337/tcp   testnet_cardano-node-ogmios_1
d96ad97371ea   postgres:11.5-alpine                                  "docker-entrypoint.s…"   2 hours ago   Up 2 hours             0.0.0.0:5433->5432/tcp, :::5433->5432/tcp                                   testnet_postgres_1

```

so I assume ```cardano-node-ogmios``` is cardano node? 

It's recent log is

```
cardano-node-ogmios_1       | [cd65224a:cardano.node.ChainDB:Notice:469] [2022-04-01 09:38:16.40 UTC] Chain extended, new tip: cfcd3ed1754bc92c3df5635174d72c3a1af617b4c498f56ddc57cf02dea04cd2 at slot 54436680
cardano-node-ogmios_1       | {"severity":"Info","timestamp":"2022-04-01T09:38:16.413009929Z","thread":"425","message":{"Health":{"tag":"HealthTick","status":{"startTime":"2022-04-01T07:17:49.586162936Z","lastKnownTip":{"slot":54436680,"hash":"cfcd3ed1754bc92c3df5635174d72c3a1af617b4c498f56ddc57cf02dea04cd2","blockNo":3441033},"lastTipUpdate":"2022-04-01T09:38:16.412683649Z","networkSynchronization":1.00000,"currentEra":"Alonzo","metrics":{"sessionDurations":{"max":0,"min":0,"mean":0},"totalMessages":3,"runtimeStats":{"currentHeapSize":712,"maxHeapSize":718,"gcCpuTime":90936167089,"cpuTime":110336360557},"activeConnections":3,"totalUnrouted":0,"totalConnections":3},"connectionStatus":"connected","currentEpoch":196,"slotInEpoch":134280}}},"version":"v5.1.0"}

```

Which meet the latest height in testnet.

**Comment by somereason** [comment]
I retired with latest commit on branch 6.2.0
After sync finished, Server is still not running.
After I restart all component by following command

```
docker-compose -p testnet down
 DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 NETWORK=testnet RESTORE_SNAPSHOT=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/12/db-sync-snapshot-schema-12-block-3429999-x86_64.tgz API_PORT=3101 HASURA_PORT=8091 OGMIOS_PORT=1338 POSTGRES_PORT=5433 METADATA_SERVER_URI="https://metadata.cardano-testnet.iohkdev.io" docker-compose -p testnet up -d --build &&docker-compose -p testnet logs -f

```

I got the error log like this. It seems server shutdown due to some sechma error

cardano-graphql_1           | {"name":"cardano-graphql","hostname":"48542de3634b","pid":1,"level":30,"module":"Server","msg":"GraphQL HTTP server at http://0.0.0.0:3100/ shutting down","time":"2022-04-03T03:31:18.998Z","v":0}
cardano-graphql_1           | (node:1) UnhandledPromiseRejectionWarning: Error: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              adaPots {\n                  reserves\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}
cardano-graphql_1           |     at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)
cardano-graphql_1           |     at step (/app/node_modules/graphql-request/dist/index.js:63:23)
cardano-graphql_1           |     at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)
cardano-graphql_1           |     at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)
cardano-graphql_1           |     at runMicrotasks (<anonymous>)
cardano-graphql_1           |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
cardano-graphql_1           | (Use `node --trace-warnings ...` to show where the warning was created)
cardano-graphql_1           | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
cardano-graphql_1           | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rhyslbw** [comment]
`docker-compose down` removes the containers, so to restart you just want to use `docker restart testnet_cardano-graphql_1`. Sorry for the delay in getting back to you, did you make any progress?

**Comment by RdeWilde** [comment]
So a restart is the way to resolve this issue? Any other way to do this?

**Comment by somereason** [comment]
> So a restart is the way to resolve this issue? Any other way to do this?

Sorry, I'm using cardano-db-sync now, It's a better choice, as you can install every module separately. Even better, you can  reduce memory usage by setting a flag. 

Trust me, query from database will not be a problem, I feel more comfortable with sql instand of graphql request.
