### ISSUE TITLE
submitTransaction error does not parse correctly

### ISSUE THREAD

**Issue by trevor-crypto** [input-output-hk/cardano-graphql#733]
When submitting an invalid transaction, the error is caught and then not parsed correctly, which leads to not being able to see the real error.

Here is the transaction and result through the graphql playground:
```
mutation {
  submitTransaction(
    transaction: "hKUAgYJYIFkPVktj1KkbUDIEWVJF7PAC_lJUMTJM4YpuLnXe2iGrAQGCglg5AHTKs5LX8_N7PfQWn29NsvrT5dq1Mox8OvjTvu4uPpuwYelkZ8-lNcPh4FIXagiMyHfrxTcfdIONGgAPQkCCWDkAdMqzktfz83s99Bafb02y-tPl2rUyjHw6-NO-7i4-m7Bh6WRnz6U1w-HgUhdqCIzId-vFNx90g40aO0bGgQIaAAKhpQSCggCBggBYHC4-m7Bh6WRnz6U1w-HgUhdqCIzId-vFNx90g42CAoKCAFgcLj6bsGHpZGfPpTXD4eBSF2oIjMh368U3H3SDjVgcSPLDZ8_oHKxmh8P3wmYT7f5zzTKUAqpc9JO7YQ8AoQCCglggo-VIxeCVD1lBxf6w7-LLhSrnC_2C1fKX8imR1EuXFR5YQO05IeXke0lHPhSLFaYYa4Xr0oVHfSHuyn8FWzvGBpUUpL1xsUloJ-QUnv0pEjSsqDDTY1H-b69nYeAWv7x3xg-CWCCX6kqjH-YMX6tx52GzW-unCdWm5dKPUpmUwQFiS-ySvVhAuBjyJLm4j85VNZfe9MhZ8tuevFwptd7Bcr4RDH6v7ZVlLaRayLhOowmL2jX7yxnJzd8Aqjef3r4L-wvaSyjOB_X2"
  ) {
    hash
  }
}
```

```
{
  "errors": [
    {
      "message": "Unexpected token i in JSON at position 184",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "submitTransaction"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "SyntaxError: Unexpected token i in JSON at position 184",
            "    at JSON.parse (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/executableSchema.js:72:59",
            "    at Array.map (<anonymous>)",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:70:56)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

https://github.com/input-output-hk/cardano-graphql/blob/f61d199da7f1de1029c37016cd82fd2658d6e2ec/packages/api-cardano-db-hasura/src/executableSchema.ts#L88

**Comment by rhyslbw** [comment]
Thanks @trevor-crypto

I've fixed this upstream https://github.com/CardanoSolutions/ogmios/pull/236, so it will be resolved here when there's a new version of Ogmios.
