### ISSUE TITLE
utxo_aggregate sum error

### ISSUE THREAD

**Issue by awesome9999** [input-output-hk/cardano-graphql#801]
I am trying to send this query to get amount of NFTs locked on address by policyId:
`query {
  utxos_aggregate(
    where: {
      _and: {
        address: { _eq: $address },
        tokens: {
          asset: {
            policyId: { _eq: "d6fe6efa7788cb70e57a91891605e3694352cabb4837e870610300e9"}
          }
        }
      }
    }
  ){ aggregate {
        sum {
        tokens {
          quantity
        }
        }
    }
  }
}`

I am trying to get count of NFTs locked on some address by policy ID using cardano graph ql.

I have this query in cardano-graphql (https://github.com/input-output-hk/cardano-graphql):

query {
  utxos_aggregate(
    where: {
      _and: {
        address: { _eq: $address },
        tokens: {
          asset: {
            policyId: { _eq: "d6fe6efa7788cb70e57a91891605e3694352cabb4837e870610300e9"}
          }
        }
      }
    }
  ){ aggregate {
        sum {
        tokens {
          quantity
        }
        }
    }
  }
}
It works well with count aggregate, but in case of sum aggregate it returns this error:

`{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Query.utxos_aggregate.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "utxos_aggregate"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Query.utxos_aggregate.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)",
            "    at executeOperation (/app/node_modules/graphql/execution/execute.js:219:122)",
            "    at executeImpl (/app/node_modules/graphql/execution/execute.js:104:14)",
            "    at Object.execute (/app/node_modules/graphql/execution/execute.js:64:35)",
            "    at /app/node_modules/apollo-server-core/dist/requestPipeline.js:261:48",
            "    at Generator.next (<anonymous>)",
            "    at /app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"
          ]
        }
      }
    }
  ],
  "data": null
}`

**Comment by siegfried** [comment]
We've got a similar issue so I'll just add to this issue.

Query:

```
query UTxO($addresses: [String]!) {
  utxos(where: { address: { _in: $addresses } }) {
    address
    txHash
    index
    value
    tokens {
      asset {
        assetId
      }
      quantity
    }
  }
}
```

Variables:
```json
{
	"addresses": [
	    "addr1q8l5hxd2kk2qd9vvl5mk7txrzezrlnsgym2utnt62lryphg5kkvr22hlffqdj63vk8nf8rje5np37v4fwlpvj4c4qryqz4z0sm"
	]
}
```

Returns:
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Token.asset.",
      "locations": [
        {
          "line": 8,
          "column": 7
        }
      ],
      "path": [
        "utxos",
        0,
        "tokens",
        0,
        "asset"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Token.asset.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:557:21)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at /app/node_modules/graphql/execution/execute.js:618:25"
          ]
        }
      }
    }
  ],
  "data": {
    "utxos": [
      null
    ]
  }
}
```

AFAIK, this issue occurs to addresses holding some tokens but not all tokens, e.g. Hosky is fine. And after like hours, some tokens become normal. My guess is that some info of native assets were missing or not syncing fast enough, even if our node has catch the tip. What is the root cause and how can we improve it?

**Comment by VladislavKudrin** [comment]
#952
